name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  version-next:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version-next: ${{ steps.reference.outputs.next-reference }}
      version-next-strict: ${{ steps.reference.outputs.next-reference }}
    steps:
      - uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #4.1.7

      - name: Next Reference
        id: reference
        uses: wearefrank/ci-cd-templates/next-reference@84b07af359071bee943bd6ff0e323f6d44d93a29 #1.0.5

  ci:
    uses: wearefrank/ci-cd-templates/.github/workflows/ci-generic.yml@84b07af359071bee943bd6ff0e323f6d44d93a29 #1.0.5
    needs:
      - version-next
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      version: ${{ needs.version-next.outputs.version-next }}

  